=== nti-de/SAGisALKISSearch/resources/config/GenericDialog/Configuration/SAGisGnDlgConfig.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="SAGisGnDlgConfig">
		<xs:complexType>
			<xs:sequence>

				<xs:element name="Container" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<!-- <xs:element type="xs:string" name="Class" minOccurs="1" maxOccurs="1"/> -->
							<xs:element type="xs:string" name="Caption" minOccurs="1" maxOccurs="1"/>
							<xs:element type="xs:string" name="CssFiles" minOccurs="0" maxOccurs="1"/>
							<xs:element type="xs:string" name="SchemaNamePlaceHolder" minOccurs="0" maxOccurs="1" default="{SCHEMA_NAME_PLACEHOLDER}"/>
							<xs:element type="xs:string" name="SchemaName" minOccurs="0" maxOccurs="1"/>
							<xs:element name="ActivityLog" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute type="xs:boolean" default="false" name="Active" use="optional"/>
									<xs:attribute type="xs:string" name="InfoLogColumn" use="optional"/>
								</xs:complexType>
							</xs:element>
							
							<xs:element name="SearchTemplate">
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element name="Queries" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Query" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element type="xs:string" name="BindTo" minOccurs="1" maxOccurs="1"/>
																<xs:element type="xs:string" name="Sql" minOccurs="1" maxOccurs="1"/>
																<xs:element type="xs:string" default="KEY" name="KeyValueField" minOccurs="0" maxOccurs="1" />
																<xs:element type="xs:string" default="CAPTION" name="CaptionValueField" minOccurs="0" maxOccurs="1" />
																<xs:element type="xs:string" default="{1} ({0})" name="CaptionFormat" minOccurs="0" maxOccurs="1" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Search" minOccurs="1" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="Sql" minOccurs="1" maxOccurs="1"/>
													<xs:element type="xs:string" name="FixedSqlWhere" minOccurs="0" maxOccurs="1" />

													<xs:element name="Parameter" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<!--<xs:attribute type="xs:string" default="" name="DataType" use="optional"/>-->
																	<xs:attribute type="xs:string" name="DbField" use="required"/>
																	<xs:attribute type="xs:string" name="FormField" use="required"/>
																	<xs:attribute type="xs:string" default="" name="DbJoinedTableName" use="optional"/>
																	<xs:attribute type="xs:string" default="" name="DbTableAlias" use="optional"/>
																	<xs:attribute type="xs:string" default="" name="DefaultValue" use="optional"/>
																	<xs:attribute type="xs:boolean" default="true" name="CaseSensitive" use="optional"/>
																	<xs:attribute type="xs:boolean" default="false" name="Range" use="optional"/>
																	<!--
																	<xs:attribute type="xs:boolean" default="true" name="Like" use="optional"/>
																	<xs:attribute type="xs:boolean" default="true" name="In" use="optional"/>
																	-->
																	<xs:attribute name="WhereCondition" default="IsEqual" use="optional">
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:enumeration value="In"/>
																				<xs:enumeration value="Like"/>
																				<xs:enumeration value="IsEqual"/>
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:attribute>
																	
																	<xs:attribute type="xs:string" default="AND" name="SqlOperator" use="optional"/>
																	<xs:attribute type="xs:string" default="String" name="DbFieldMgPropertyType" use="optional"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										
										<xs:element type="xs:string" name="SearchTemplate" maxOccurs="1" minOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							
							<xs:element name="InfoTemplate">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:boolean" default="true" name="Editable" minOccurs="0" maxOccurs="1"/>
										<xs:element name="Panels">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Panel" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:sequence>
																<xs:element type="xs:string" name="Caption"/>
																<xs:element type="xs:string" name="Authorisation" minOccurs="0" maxOccurs="1"/>
																<xs:element type="xs:boolean" default="true" name="Active" minOccurs="0" maxOccurs="1"/>
																<xs:element type="xs:boolean" default="false" name="HideIfQueryIsEmpty" minOccurs="0" maxOccurs="1"/>
																<xs:element type="xs:boolean" default="true" name="ShowDatacount" minOccurs="0" maxOccurs="1"/>
																<xs:element type="xs:integer" name="height" minOccurs="0" maxOccurs="1" default="600" />
																<xs:element name="Query">
																	<xs:complexType>
																		<xs:sequence>
																			
																			<xs:element type="xs:string" name="Name" minOccurs="0" maxOccurs="1" />
																			<xs:element type="xs:boolean" name="AllowEmpty" minOccurs="0" maxOccurs="1" default="true" />
																			<xs:element type="xs:integer" name="AllowMaxResults" minOccurs="0" maxOccurs="1" />
																			<xs:element type="xs:string" name="Parent" minOccurs="0" maxOccurs="1" />
																			<xs:choice>
																				<xs:element type="xs:string" name="Sql" minOccurs="1" maxOccurs="1" />
																				<xs:element name="Intersection" minOccurs="1" maxOccurs="1" >
																					<xs:complexType>
																						<xs:sequence>
																							<xs:element type="xs:string" name="TargetFeatureClass" minOccurs="0" maxOccurs="1" />
																							<xs:element type="xs:string" name="OrderBy" minOccurs="0" maxOccurs="1"/>
																							<xs:element type="xs:string" name="Filter" minOccurs="0" maxOccurs="1"/>
																							<xs:element type="xs:integer" name="MgFeatureSpatialOperation" minOccurs="0" maxOccurs="1" default="-1"/>
																							<xs:element type="xs:string" name="Property" minOccurs="0" maxOccurs="unbounded"/>
																							
																							<xs:element name="Translation" maxOccurs="unbounded" minOccurs="0">
																								<xs:complexType>
																									<xs:sequence>
																										<xs:element type="xs:string" name="Sql" minOccurs="1" maxOccurs="1" />
																										<xs:element type="xs:string" name="FromColumn" minOccurs="1" maxOccurs="1" />
																										<xs:element type="xs:string" name="ValueColumn" minOccurs="1" maxOccurs="1" />
																										<xs:element type="xs:string" name="IdColumn" minOccurs="1" maxOccurs="1" />
																									</xs:sequence>
																								</xs:complexType>
																							</xs:element>
																						</xs:sequence>
																					</xs:complexType>
																				</xs:element>
																			</xs:choice>
																			
																			<xs:element name="ShowInMap" minOccurs="0" maxOccurs="1" >
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element type="xs:string" name="LayerFeatureClassName" minOccurs="1" maxOccurs="1" />
																						<xs:element type="xs:string" name="BindTo" minOccurs="1" maxOccurs="1"/>
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																			
																			
																		</xs:sequence>
																		<xs:attribute type="xs:string" name="JsDataColumns" />
																	</xs:complexType>
																</xs:element>

																<xs:element name="Bindings" maxOccurs="unbounded" minOccurs="0">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element type="xs:boolean" default="true" name="Active" minOccurs="0" maxOccurs="1"/>
																			<xs:element type="xs:string" name="Caption" minOccurs="0" maxOccurs="1" />
																			<xs:element type="xs:string" name="Sql" minOccurs="1" maxOccurs="1" />
																			<xs:element type="xs:string" name="BindTo" minOccurs="1" maxOccurs="1"/>
																			<xs:element type="xs:string" name="Authorisation" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="HeaderText" maxOccurs="unbounded" minOccurs="0">
																				<xs:complexType>
																					<xs:simpleContent>
																						<xs:extension base="xs:string">
																							<xs:attribute type="xs:string" name="From" use="required"/>
																							<xs:attribute type="xs:string" name="To" use="required"/>
																						</xs:extension>
																					</xs:simpleContent>
																				</xs:complexType>
																			</xs:element>
																			<xs:element type="xs:boolean" name="ShowHeaderWhenEmpty" minOccurs="0" maxOccurs="1" default="false" />
																			
																			<xs:element name="JavaScriptClick" maxOccurs="unbounded" minOccurs="0">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element type="xs:string" name="Column" minOccurs="1" maxOccurs="1" />
																						<xs:element type="xs:string" name="JsFn" minOccurs="1" maxOccurs="1" />
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>

																<xs:choice>
																	<xs:element type="xs:string" name="ItemTemplate" maxOccurs="1" minOccurs="1" />

																	<xs:element name="NoItemTemplate" maxOccurs="1" minOccurs="1" >
																		<xs:complexType>
																			<xs:sequence>
																				<xs:element name="ColumnNameTranslation" maxOccurs="unbounded" minOccurs="0">
																					<xs:complexType>
																						<xs:simpleContent>
																							<xs:extension base="xs:string">
																								<xs:attribute type="xs:string" name="From" use="required"/>
																								<xs:attribute type="xs:string" name="To" use="required"/>
																							</xs:extension>
																						</xs:simpleContent>
																					</xs:complexType>
																				</xs:element>
																			</xs:sequence>
																		</xs:complexType>
																	</xs:element>
																	
																</xs:choice>

																<xs:element type="xs:string" name="FooterTemplate" maxOccurs="1" minOccurs="0" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>



			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nti-de/SAGisALKISSearch/resources/config/GenericDialog/Configuration/AX_FLURSTUECK_SQLITE.xml
<?xml version="1.0" encoding="utf-8" ?>

<SAGisGnDlgConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="SAGisGnDlgConfig.xsd">
	<Container>
		<Caption>Flurstück</Caption>
		<SearchTemplate>
			<Search>
				<Sql></Sql>
			</Search>
			<SearchTemplate></SearchTemplate>
		</SearchTemplate>

		<!--
		*
		* InfoTemplate
		*
		-->
		<InfoTemplate>
			<Editable>false</Editable>
			<Panels>
				<!-- Allgemein -->
				<Panel>
					<Caption>Allgemein</Caption>
					<ShowDatacount>false</ShowDatacount>
					<Query>
						<Name>AX_FLURSTUECK</Name>
						<AllowEmpty>false</AllowEmpty>
						<AllowMaxResults>1</AllowMaxResults>
						<Sql><![CDATA[
								SELECT a.ID, a.FID, a.GEMEINDEZUGEHOERIGKEIT, a.ZEITPUNKTDERENTSTEHUNG, a.GEMARKUNG,
									a.AMTLICHEFLAECHE, a.FLURNUMMER, a.FLURSTUECKSNUMMER_ZAEHLER, a.FLURSTUECKSNUMMER_NENNER,
									a.FLURSTUECKSKENNZEICHEN, a.AREA, a.FLURSTUECKSFOLGE, a.ZUSTAENDIGESTELLE, a.ANLASS1, a.ANLASS2,
									a.RECHTSBEHELFSVERFAHREN,
									(CASE a.RECHTSBEHELFSVERFAHREN WHEN 0 THEN 'Nein' WHEN 1 THEN 'Ja' ELSE 'Keine Angabe' END) as XRECHTSBEHELFSVERFAHREN,
									a.ABWEICHENDERRECHTSZUSTAND,
									(CASE a.ABWEICHENDERRECHTSZUSTAND WHEN 0 THEN 'Nein' WHEN 1 THEN 'Ja' ELSE 'Keine Angabe' END) as XABWEICHENDERRECHTSZUSTAND,
									a.ZWEIFELHAFTERFLURSTUECKSNA,
									(CASE a.ZWEIFELHAFTERFLURSTUECKSNA WHEN 0 THEN 'Nein' WHEN 1 THEN 'Ja' ELSE 'Keine Angabe' END) as XZWEIFELHAFTERFLURSTUECKSNA,
									b.SCHLUESSELGESAMT as GEMEINDESCHLUESSEL, b.BEZEICHNUNG as GEMEINDEBEZEICHNUNG,
									c.SCHLUESSELGESAMT as GEMARKUNGSCHLUESSEL, c.BEZEICHNUNG as GEMARKUNGBEZEICHNUNG,
									d.BEZEICHNUNG as ZUSTAENDIGESTELLEBEZ,
									e.VALUE AS ANLASS1_VALUE, f.VALUE AS ANLASS2_VALUE
								FROM AX_FLURSTUECK a
									LEFT OUTER JOIN AX_GEMEINDE b ON ( b.GEMEINDEKENNZEICHEN = a.GEMEINDEZUGEHOERIGKEIT )
									LEFT OUTER JOIN AX_GEMARKUNG c ON ( c.SCHLUESSEL = a.GEMARKUNG )
									LEFT OUTER JOIN AX_DIENSTSTELLE d ON ( d.SCHLUESSEL = a.ZUSTAENDIGESTELLE )
									LEFT OUTER JOIN AA_ANLASSART_TBD e ON ( e.SHORT_VALUE = a.ANLASS1 )
									LEFT OUTER JOIN AA_ANLASSART_TBD f ON ( f.SHORT_VALUE = a.ANLASS2 )
								WHERE a.FID = {SELECTED_MAP_ITEM}
						]]></Sql>
					</Query>

					<!-- Eigentümer Übersicht -->
					<Bindings>
						<Sql><![CDATA[
							SELECT
								d.VALUE as BUCHUNGSART_VALUE ,
								b.VALUE as EIGENTUEMERART_VALUE,
								CONCAT(a.ANTEIL_ZAEHLER::int, '/', a.ANTEIL_NENNER::int) as X_ANTEILE,
								CONCAT(c.VALUE, ' ', a.VORNAME, ' ', a.NACHNAMEODERFIRMA) as X_EIGENTUEMER
							FROM (
								select
									me.FID, me.FSID,me.DIREKT,me.D_BUART,me.D_BBID,me.D_BLART,me.I_BUART,me.I_BBID,me.I_BLART,me.NNID,
									me.BBID,me.PEID,me.LAUFENDENUMMERNACHDIN1421,me.NUMMER,me.ANTEIL_ZAEHLER,me.ANTEIL_NENNER,
									me.ARTDERRECHTSGEMEINSCHAFT,me.EIGENTUEMERART,

									pe.FID FID_PE, pe.ID ID_PE, pe.LZB LZB_PE, pe.NACHNAMEODERFIRMA, pe.ANREDE, pe.VORNAME, pe.NAMENSBESTANDTEIL,
									pe.AKADEMISCHERGRAD, pe.GEBURTSNAME, pe.GEBURTSDATUM, pe.WOHNORTODERSITZ, pe.BERUF, pe.SONSTIGEEIGENSCHAFTEN,
									pe.HAUSHALTSSTELLELANDESGRUND, pe.QUALITAETSANGABEN
								FROM ME_FS_PE me
									left outer JOIN AX_FLURSTUECK fs on ( fs.ID = me.FSID AND fs.LZE is null )
									inner JOIN AX_PERSON pe on ( pe.ID = me.PEID AND pe.LZE is null )
							) a
								LEFT OUTER JOIN AX_EIGENTUEMERART_TBD b ON ( b.SHORT_VALUE = a.EIGENTUEMERART )
								LEFT OUTER JOIN AX_ANREDE_PERSON_TBD c ON ( c.SHORT_VALUE = a.ANREDE )
								LEFT OUTER JOIN AX_BUCHUNGSART_TBD d ON ( d.SHORT_VALUE = a.I_BUART )
							WHERE a.FSID = '{ID}'
						]]></Sql>
						
						<BindTo>dataV_EIGENTUEMER_DIST_OVERVIEW</BindTo>
						<HeaderText From="buchungsart_value" To="Buchungsart"/>
						<HeaderText From="eigentuemerart_value" To="Eigentümerart"/>
						<HeaderText From="x_anteile" To="Anteilsverhältnis"/>
						<HeaderText From="x_eigentuemer" To="Eigentümer"/>
					</Bindings>

					<!-- Historisches Flurstueck -->
					<Bindings>
						<Sql>![CDATA[
						SELECT
						 a.GEMARKUNG, a.FLURNUMMER, a.FLURSTUECKSNUMMER_ZAEHLER, a.FLURSTUECKSNUMMER_NENNER, a.FLURSTUECKSFOLGE,
						 a.FLURSTUECKSKENNZEICHEN, a.AMTLICHEFLAECHE, a.ZEITPUNKTDERENTSTEHUNG,
							 c.SCHLUESSEL as GEMARKUNGSCHLUESSEL, c.BEZEICHNUNG as GEMARKUNGBEZEICHNUNG
						FROM AX_HISTORISCHESFST a
						 LEFT OUTER JOIN AX_GEMARKUNG c ON ( c.SCHLUESSEL = a.GEMARKUNG )
						WHERE NACHFOLGERFLURSTUECKSKENNZ = '{FLURSTUECKSKENNZEICHEN}'
						]]</Sql>
						<BindTo>dataAX_HISTORISCHESFST</BindTo>
						<HeaderText From="flurstuecksfolge" To="Flurstücksfolge"/>
						<HeaderText From="flurstueckskennzeichen" To="Flurstückskennzeichen"/>
						<HeaderText From="amtlicheflaeche" To="Amtl. Fläche"/>
						<HeaderText From="zeitpunktderentstehung" To="Entstehung"/>
					</Bindings>
					
					<ItemTemplate>ItemTemplates\AX_FLURSTUECK\AX_FLURSTUECK</ItemTemplate>
				</Panel>

				<!-- Buchungsstellen/-blätter -->
				<Panel>
					<Caption>Buchungsstellen/-blätter</Caption>
					<Query>
						<Name>BUCHUNGSSTELLEN</Name>
						<Parent>AX_FLURSTUECK</Parent>
						<Sql><![CDATA[
							SELECT
							   Distinct(me.I_BSID) AS BSID
								, bs.LAUFENDENUMMER
								, bs.ANTEIL_ZAEHLER
								, bs.ANTEIL_NENNER
								, bs.LZB
								, bs.buchungsart
								, tbdBuchungsArt.VALUE as buchungsart_VALUE
							FROM me_fs_bb me
							LEFT JOIN ax_buchungsstelle bs on (bs.LZE is null and me.I_BSID = bs.ID)
							LEFT JOIN ax_buchungsart_tbd tbdBuchungsArt on(tbdBuchungsArt.SHORT_VALUE = bs.buchungsart)
							WHERE me.FSID = '{ID}'
							ORDER BY bs.LAUFENDENUMMER
						]]></Sql>
					</Query>

					<Bindings>
						<Sql><![CDATA[
							SELECT
							bb.BUCHUNGSBLATTKENNZEICHEN,
							bb.BUCHUNGSBLATTNUMMERMITBUCH,
							bb.BLATTART,
							bbBezirk.SCHLUESSELGESAMT as BB_BEZIRK_KEY,
							bbBezirk.BEZEICHNUNG as BB_BEZIRK_VALUE,
							(bbBezirk.SCHLUESSELGESAMT || '/' || bbBezirk.BEZEICHNUNG) as BB_BEZIRK_SCHL_VALUE,
							tbdBlattart.VALUE as BLATTART_VALUE,
							(bb.BLATTART || '/' || tbdBlattart.VALUE) as BLATTART_SCHL_VALUE
							FROM me_bs_bb me
							 LEFT JOIN ax_buchungsblatt bb on (bb.LZE is null and bb.id = me.BBID)
							 LEFT OUTER JOIN AX_BUCHUNGSBLATTBEZIRK bbBezirk ON (bbBezirk.SCHLUESSEL = bb.BUCHUNGSBLATTBEZIRK)
							LEFT OUTER JOIN AX_BLATTART_TBD tbdBlattart ON(tbdBlattart.SHORT_VALUE = bb.BLATTART)
							WHERE me.bsid = '{BSID}'
						]]></Sql>
						<BindTo>dataBS_BUCHUNGSBLATT</BindTo>
						<HeaderText From="BUCHUNGSBLATTKENNZEICHEN" To="Buchungsblatt"/>
						<HeaderText From="BB_BEZIRK_SCHL_VALUE" To="Buchungsblattbezirk"/>
						<HeaderText From="BUCHUNGSBLATTNUMMERMITBUCH" To="Buchungsblattnummer"/>
						<HeaderText From="BLATTART_SCHL_VALUE" To="Blattart"/>
					</Bindings>

					<ItemTemplate>ItemTemplates\AX_FLURSTUECK\BUCHUNGSSTELLEN</ItemTemplate>
				</Panel>

				<!-- Eigentümer nach Buchungsblättern -->
				<Panel>
					<Caption>Eigentümer nach Buchungsblättern</Caption>
					<Query>
						<Name>V_EIGENTUEMER_FS</Name>
						<Parent>AX_FLURSTUECK</Parent>
						<Sql><![CDATA[
							SELECT
							me.PEID, me.LAUFENDENUMMERNACHDIN1421,
							me.ANTEIL_ZAEHLER, me.ANTEIL_NENNER, me.ARTDERRECHTSGEMEINSCHAFT, me.EIGENTUEMERART,
							pe.AKADEMISCHERGRAD, pe.VORNAME, pe.BERUF, pe.NACHNAMEODERFIRMA, pe.GEBURTSNAME,
							pe.NAMENSBESTANDTEIL, pe.GEBURTSDATUM, pe.WOHNORTODERSITZ, pe.HAUSHALTSSTELLELANDESGRUND, pe.SONSTIGEEIGENSCHAFTEN,
							b.VALUE as EIGENTUEMERART_VALUE,
							c.VALUE as ANREDE_VALUE,
							d.VALUE as BUCHUNGSART_VALUE,
							e.BUCHUNGSBLATTKENNZEICHEN, e.BUCHUNGSBLATTBEZIRK, e.BUCHUNGSBLATTNUMMERMITBUCH,
							f.SCHLUESSELGESAMT as BB_BEZIRK_KEY, f.BEZEICHNUNG AS BB_BEZIRK_VALUE,
							bs.ANTEIL_ZAEHLER as BS_ANTEIL_ZAEHLER, bs.ANTEIL_NENNER as BS_ANTEIL_NENNER
							FROM ME_FS_PE me
							--left outer JOIN AX_FLURSTUECK fs on fs.ID = me.FSID AND fs.LZE is null
							inner JOIN AX_PERSON pe on pe.ID = me.PEID AND pe.LZE is null
							LEFT OUTER JOIN AX_EIGENTUEMERART_TBD b ON ( b.SHORT_VALUE = me.EIGENTUEMERART )
							LEFT OUTER JOIN AX_ANREDE_PERSON_TBD c ON ( c.SHORT_VALUE = pe.ANREDE )
							LEFT OUTER JOIN AX_BUCHUNGSART_TBD d ON ( d.SHORT_VALUE = me.I_BUART )
							LEFT OUTER JOIN AX_BUCHUNGSBLATT e ON ( e.ID = me.BBID )
							LEFT OUTER JOIN AX_BUCHUNGSBLATTBEZIRK f ON ( f.SCHLUESSEL = e.BUCHUNGSBLATTBEZIRK )
							LEFT OUTER JOIN ME_BZ mebz ON (mebz.TABELLE = 'AX_Flurstueck' AND mebz.LZE is null AND mebz.ART = 'istGebucht' AND mebz.ID = me.FSID)
							INNER JOIN AX_BUCHUNGSSTELLE bs ON mebz.ZID = bs.ID AND bs.LZE IS NULL
							WHERE me.FSID = '{ID}'
							ORDER BY e.BUCHUNGSBLATTKENNZEICHEN ASC , LAUFENDENUMMERNACHDIN1421
						]]></Sql>
					</Query>

					<Bindings>
						<Sql><![CDATA[
							SELECT
								a.QUALITAETSANGABEN , a.POSTLEITZAHLPOSTZUSTELLUNG, a.ORT_POST, a.ORTSTEIL,
								a.STRASSE, a.HAUSNUMMER, a.POSTLEITZAHLPOSTFACH, a.POSTFACH
							FROM AX_ANSCHRIFT a
								inner join ME_PE_AS me on a.ID = me.ASID
							WHERE a.LZE is null AND me.PEID = '{PEID}'
						]]></Sql>
						<BindTo>dataV_ANSCHRIFT_PE</BindTo>
						<HeaderText From="QUALITAETSANGABEN" To="Qualitätsangaben"/>
						<HeaderText From="POSTLEITZAHLPOSTZUSTELLUNG" To="PLZ"/>
						<HeaderText From="ORT_POST" To="Ort"/>
						<HeaderText From="ORTSTEIL" To="Ortsteil"/>
						<HeaderText From="STRASSE" To="Strasse"/>
						<HeaderText From="HAUSNUMMER" To="Nr"/>
						<HeaderText From="POSTLEITZAHLPOSTFACH" To="PLZ Postfach"/>
						<HeaderText From="POSTFACH" To="Postfach"/>
					</Bindings>

					<ItemTemplate>ItemTemplates\AX_FLURSTUECK\V_EIGENTUEMER_FS</ItemTemplate>
				</Panel>
				
				<!-- Buchungsblätter des Flurstücks -->
				<Panel>
					<Caption>Buchungsblätter</Caption>
					<Query>
						<Name>V_BUCHUNGSBLATT_FS</Name>
